name: Build Tomcat

on: push

jobs: 
  build:

    runs-on: ubuntu-latest

    steps: 
      - name: check out tomcat-users.xml
        uses: actions/checkout@v2

      - name: List project files and java version
        run: |
            ls -ltr
            java -version

      - name: Check out Apache Tomcat
        uses: actions/checkout@v2
        with:
          repository: apache/tomcat # Repository name with owner
          ref: master               # The branch, tag or SHA to checkout
          path: ./tomcat            # Relative path under $GITHUB_WORKSPACE

      - name: Setup Java 9
        uses: actions/setup-java@v1
        with: 
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64

      - name: List project files and java version
        run: |
            ls -ltr
            java -version

      - name: Copy tomcat-users.xml into Tomcat configuration directory
        run: cp -v tomcat-users.xml ./tomcat/conf/tomcat-users.xml

      - name: compile Tomcat
        run: |
            cd ./tomcat
            ant