name: Pipeline

on: push

jobs:
  test-script:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run hihi script
        run: node hello.js

  create-artifact:
    runs-on: ubuntu-latest
    needs: test-script
    steps: 
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with: 
          name: hello-script
          path: hello.js